# Generated by Django 3.0.2 on 2020-01-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mothers_name', models.CharField(max_length=50)),
                ('fathers_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=50)),
                ('date_of_birth', models.DateField()),
                ('education', models.CharField(blank=True, max_length=50, null=True)),
                ('occupation', models.CharField(max_length=50)),
                ('post', models.CharField(blank=True, max_length=50, null=True)),
                ('citizenship_number', models.IntegerField(unique=True, verbose_name='Citizenship Number')),
                ('citizenship_issued_district', models.CharField(max_length=50)),
                ('passport_number', models.IntegerField(verbose_name='Passport Number')),
                ('blood_group', models.CharField(blank=True, max_length=6, null=True)),
                ('present_state', models.CharField(max_length=50)),
                ('present_zone', models.CharField(max_length=50)),
                ('present_district', models.CharField(choices=[('janakpur', 'Janakpur'), ('bhaktapur', 'Bhaktapur'), ('kathmandu', 'Kathmandu'), ('lalitpur', 'Lalitpur')], max_length=255)),
                ('present_rmm', models.CharField(max_length=255)),
                ('present_ward', models.IntegerField(verbose_name='ward number')),
                ('present_tole', models.CharField(max_length=255)),
                ('present_block', models.IntegerField(verbose_name='block number')),
                ('present_contact', models.CharField(max_length=15)),
                ('permanent_state', models.CharField(max_length=50)),
                ('permanent_zone', models.CharField(max_length=50)),
                ('permanent_district', models.CharField(choices=[('janakpur', 'Janakpur'), ('bhaktapur', 'Bhaktapur'), ('kathmandu', 'Kathmandu'), ('lalitpur', 'Lalitpur')], max_length=255)),
                ('permanent_rmm', models.CharField(max_length=255)),
                ('permanent_ward', models.IntegerField(verbose_name='ward number')),
                ('permanent_tole', models.CharField(max_length=255)),
                ('permanent_block', models.IntegerField(verbose_name='block number')),
                ('permanent_contact', models.CharField(max_length=15)),
                ('voting_state', models.CharField(max_length=50)),
                ('voting_district', models.CharField(choices=[('janakpur', 'Janakpur'), ('bhaktapur', 'Bhaktapur'), ('kathmandu', 'Kathmandu'), ('lalitpur', 'Lalitpur')], max_length=255)),
                ('voting_rmm', models.CharField(max_length=255)),
                ('voting_ward', models.IntegerField(verbose_name='ward number')),
                ('voting_tole', models.CharField(max_length=255)),
                ('voting_booth', models.IntegerField(verbose_name='booth number')),
                ('voting_country', models.CharField(max_length=255)),
                ('voting_email', models.EmailField(max_length=255, verbose_name='email address')),
                ('email', models.EmailField(max_length=255, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
