# Generated by Django 3.0.2 on 2020-01-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200130_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='permanent_ward',
            field=models.IntegerField(blank=True, null=True, verbose_name='ward number'),
        ),
    ]
