# Generated by Django 3.0.2 on 2020-01-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200130_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passport_number',
            field=models.IntegerField(null=True, verbose_name='Passport Number'),
        ),
    ]
