# Generated by Django 3.0.2 on 2020-01-30 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200130_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blood_group',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=6),
            preserve_default=False,
        ),
    ]
